name: 'Check Plugin with PCP'
on:
  pull_request:
    branches:
      - trunk
      - develop
      - main

jobs:
  pcp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.json', 'composer.lock') }}
          restore-keys: |
            composer-

      - name: Install Composer Dependencies
        run: composer install --no-scripts --no-progress --prefer-dist

      - name: Run plugin check
        uses: wordpress/plugin-check-action@v1
        with:
          exclude-files: '.gitignore'
